prow/cmd/entrypoint: fix local umask error
Previous to this change, on my development machine the TestCopy test
would fail as follows:

    $ ./hack/make-rules/go-test/unit.sh prow/cmd/entrypoint/...
    + mkdir -p /usr/local/google/home/linusa/go/src/k8s.io/test-infra/_output
    + /usr/local/google/home/linusa/go/src/k8s.io/test-infra/_bin/gotestsum --junitfile=/usr/local/google/home/linusa/go/src/k8s.io/test-infra/_output/junit-unit.xml -- -count=1 -race ./prow/cmd/entrypoint/...
    ✖  prow/cmd/entrypoint (27ms)

    === Failed
    === FAIL: prow/cmd/entrypoint TestCopy/base (0.00s)
    time="2023-06-13T17:19:59-07:00" level=info msg="src is /tmp/TestCopy3391565894/001/base"
        main_test.go:58: File mode mismatch. Want: -rw-r--r--, got: -rw-r-----
        --- FAIL: TestCopy/base (0.00s)

    === FAIL: prow/cmd/entrypoint TestCopy/another-mode (0.00s)
    time="2023-06-13T17:19:59-07:00" level=info msg="src is /tmp/TestCopy3391565894/001/another-mode"
        main_test.go:58: File mode mismatch. Want: -rwxr-xr-x, got: -rwxr-x---
        --- FAIL: TestCopy/another-mode (0.00s)

    === FAIL: prow/cmd/entrypoint TestCopy (0.00s)

    DONE 3 tests, 3 failures in 0.524s

This is because the file mode permissions that result are outside of
Go's control and is system-dependent (it's how POSIX works) [1]. This
change makes it so that we set umask to a standard value, 0022. The
manpage for the umask syscall says [2]:

    The typical default value for the process umask is
    S_IWGRP | S_IWOTH (octal 022).

[1] https://stackoverflow.com/a/41565509/437583
[2] https://man7.org/linux/man-pages/man2/umask.2.html