Fix hourly_maintenance.py error when dangling images exist.
Docker prints each dangling image with a trailing newline, which made us
attempt to delete the '' image, causing:

Error response from daemon: image name cannot be blank
Error: failed to remove images: []

Or, in Python:

    >>> '415c146af238\n'.split('\n')
    ['415c146af238', '']
    >>> '415c146af238\n'.split()
    ['415c146af238']