Enable dind in cluster-autoscaler E2E periodic tests
Lack of dind caused tests to fail:
Building and pushing image...
GOOS=linux docker buildx build --pull --platform linux/amd64 \
	--build-arg "GOARCH=amd64" \
	-t gcr.io/k8s-infra-e2e-boskos-027/cluster-autoscaler-amd64:dev-d3df28b24-1770201141 \
	-f Dockerfile .
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?