boilerplate: fix test failure
The additional newlines in the boilerplate was causing:

======================================================================
FAIL: test_boilerplate (__main__.TestBoilerplate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/markmc/git/kubernetes/test-infra/./hack/boilerplate/verify_boilerplate_test.py", line 58, in test_boilerplate
    self.assertEqual(output, expected)
AssertionError: '3 files have incorrect boilerplate headers:\nfail.go\nfail.py\npass.py\n' != '2 files have incorrect boilerplate headers:\nfail.go\nfail.py\n'
- 3 files have incorrect boilerplate headers:
? ^
+ 2 files have incorrect boilerplate headers:
? ^
  fail.go
  fail.py
- pass.py