Enable privileged mode for CA periodic E2E tests
After enabling dind preset E2E tests keep failing with:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Based on other job configs, dind needs privileged mode to work.
It should have been added together with dind preset.