kubernetes-csi: need patch number in Kubernetes version for e2e.test
While the patch number no longer matters for the cluster setup, it's
still needed for checking out the E2E tests of the Kubernetes release:

Mon Jan 25 18:57:32 UTC 2021 go1.15.5 /home/prow/go/src/k8s.io/kubernetes$ git checkout v1.17
error: pathspec 'v1.17' did not match any file(s) known to git
ERROR: checking out https://github.com/kubernetes/kubernetes v1.17 failed

We could go back to specifying Kubernetes releases with
major/minor/patch number inside the gen-jobs.sh script. But so far
tests typically haven't been updated after the initial release, so
appending .0 seems simpler than that.