triage: upgrade to python3
ci-test-infra-triage job is failing with:

```bash
 ImportError: No module named enum
```

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-triage/1573399794209001472/build-log.txt

Bumping python to v3 expecting we can get missing python package.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>