cve-feed: update container image in job
The official CVE feed job started failing on September 12th and the reason is
that we install a python dependency at runtime (requests) and the image started
to be really old and we can guess something changed related to that APT
repository hosting that python stuff. The error was the following:

        E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/d/dpkg/dpkg-dev_1.20.14_all.deb  404  Not Found [IP: 151.101.2.132 80]
        E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/e/expat/libexpat1-dev_2.2.10-2%2bdeb11u7_amd64.deb  404  Not Found [IP: 151.101.2.132 80]
        E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/s/setuptools/python3-pkg-resources_52.0.0-4%2bdeb11u2_all.deb  404  Not Found [IP: 151.101.2.132 80]
        E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
        ./fetch-cve-feed.sh: line 30: pip3: command not found
        Traceback (most recent call last):
          File "/home/prow/go/src/github.com/kubernetes/sig-security/sig-security-tooling/cve-feed/hack/fetch-official-cve-feed.py", line 19, in <module>
            import requests
        ModuleNotFoundError: No module named 'requests'

Let's use an image that is maintained and widely used within that repo even if                                                                               it might be a bit too large for our use case (and we still need to install
stuff at runtime), at least it already contains the gcloud kit.