🐛 Add missing perf-tests extra_refs for the aws/kops/500-node periodic job
```
F0828 22:51:39.943563    6334 cl2.go:135] failed to run clusterloader2 tester: chdir /home/prow/go/src/k8s.io/perf-tests/clusterloader2: no such file or directory
Error: exit status 255
```

Signed-off-by: Davanum Srinivas <davanum@gmail.com>