Follow github changes after updating
`go vet` fails due to github library changes::

k8s.io/test-infra/ghclient
 ghclient/core.go:60:14: cannot use client.Repositories
   (type *github.RepositoriesService) as type repositoryService
   in field value:
 *github.RepositoriesService does not implement repositoryService
   (wrong type for ListCollaborators method)
   have ListCollaborators(context.Context, string, string, *github.ListCollaboratorsOptions)
      ([]*github.User *github.Response, error)
   want ListCollaborators(context.Context, string, string, *github.ListOptions)
      ([]*github.User, *github.Response error)

This patch makes ghclient follow these changes.